### ISSUE TITLE
Invalid requirements file format

### ISSUE THREAD

**Issue by hrvolapeter** [MuhammedBuyukkinaci/TensorFlow-Sentiment-Analysis-on-Amazon-Reviews-Data#4]
The format of requirements file doesn't meet expected format for pip3 requirements file. You can generate content of this file automatically using `pip3 freeze`

**Comment by MuhammedBuyukkinaci** [comment]
Your pip3 version may differ. Mine is below:

$ pip3 --version
pip 19.0.1 from /home/muhammed/.local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by hrvolapeter** [comment]
Mine version is 19.1.1. The example in readme is using wrong format requirements file is installed with `pip3 install -r requirements.txt` and format of file is as follows:
```
tensorflow==1.12.0
pandas==0.23.4
```
What you have looks more like bash script

**Comment by MuhammedBuyukkinaci** [comment]
I updated it as

`pip3 install -r requirements.txt`
